services:
  tauri-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vrcjournal-dev
    volumes:
      - .:/app
      - cargo-cache:/root/.cargo/registry
      - cargo-git:/root/.cargo/git
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /mnt/wslg:/mnt/wslg:rw
    environment:
      - RUST_BACKTRACE=1
      - CARGO_HOME=/root/.cargo
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - PULSE_SERVER=${PULSE_SERVER}
    stdin_open: true
    tty: true
    command: /bin/bash

volumes:
  cargo-cache:
  cargo-git:
